### ISSUE TITLE
add conceal for `\sqrt`, `\log` and other non symbol math notation, and size commands

### ISSUE THREAD

**Issue by life00** [ryleelyman/latex.nvim#11]
Hi! Just want to say a giant thank you for this project. I was searching for something like this for the past year or so, and randomly found your project from your comment in treesitter query related issue/PR.

There are few things I would want to also be concealed. Those include:

Conceal roots with √, ∛, ∜, or figure out something equivalent for `\sqrt[a]{b}` .

Replace non symbol math notation like `\log`, `\sin`, `\cos`, `\lim` etc. with just `log`, `sin`, `cos`.

Fully remove size commands like `\displaystyle`. I regularly use it to properly display sums and integrals and its pretty annoying that they stay there.

I don't have much experience with treesitter queries, however I might try implementing some of this too.

**Comment by robbielyman** [comment]
hi! i'd happily take a look at a PR. unfortunately, i'm not using neovim much these days, so i don't plan to work on this myself. thanks for your kind words!
