### ISSUE TITLE
Conceal of user defined command for fonts

### ISSUE THREAD

**Issue by Fireond** [ryleelyman/latex.nvim#7]
It seems that treesitter has conceal for font like `\mathbf` to be bold font, but is there any way to define conceal for user defined commands? For example, I define `\vb` to be `\mathbf`, how can I let `\vb{A}` becomes `A(bold)`? Thanks!

**Comment by robbielyman** [comment]
I believe you would want to mimic [nvim-treesitter's](https://github.com/nvim-treesitter/nvim-treesitter/blob/78b3a8229356e7d7eb62d1da4fe723dcff16076e/queries/latex/highlights.scm#L198-L201) command: so something like this, which you would put in your runtimepath as `after/queries/latex/highlights.scm`

```scheme
((generic_command
  command: (command_name) @_name
  arg: (curly_group (_) @text.strong))
  (#match? @_name "^(\\\\vb)$"))
```

**Comment by Fireond** [comment]
> I believe you would want to mimic [nvim-treesitter's](https://github.com/nvim-treesitter/nvim-treesitter/blob/78b3a8229356e7d7eb62d1da4fe723dcff16076e/queries/latex/highlights.scm#L198-L201) command: so something like this, which you would put in your runtimepath as `after/queries/latex/highlights.scm`
> 
> ```scheme
> ((generic_command
>   command: (command_name) @_name
>   arg: (curly_group (_) @text.strong))
>   (#match? @_name "^(\\\\vb)$"))
> ```

Thanks! But I add but it does not work, is there anything I need to do?

**Comment by robbielyman** [comment]
Ahh, I'm sorry, I gave bad advice. Instead of `after/queries/latex/highlights.scm` you want just `queries/latex/highlights.scm`
and the file ought to have `;; extends` at the top, so

```lisp
;; extends
((generic_command
  command: (command_name) @_name
  arg: (curly_group (_) @text.strong))
  (#match? @_name "^(\\\\vb)$"))
```

**Comment by Fireond** [comment]
Thanks!
