### ISSUE TITLE
Markdown mathmode

### ISSUE THREAD

**Issue by haoming-li-ling** [ryleelyman/latex.nvim#8]
Math environments in latex code blocks in a markdown file are correctly detected. 
However, markdown math regions denoted through `$ $`, `$$ $$`, `$$$ $$$`, are not detected correctly; the math mode imaps are not triggered in them.

**Comment by robbielyman** [comment]
i'd happily accept a PR to fix this, but since I'm not using neovim as my daily latex driver anymore, I'm not inclined to work on this myself.
