### ISSUE TITLE
conceal queries interfere with syntax highlighting

### ISSUE THREAD

**Issue by underscore-j** [ryleelyman/latex.nvim#9]
The use of `@text.math` in the queries used for conceal causes everything captured by this expression to be highlighted as `@text.math`.
This breaks highlighting for any valid command in a math environment (not just those that have conceal applied to them).

This can be fixed by using a different name for the capture group.

(I'll be happy to submit a PR for this, but I wanted to make sure this isn't intentional, and I'm also not sure what names should be used for the capture instead - any name seems to be valid, but I haven't yet found any instructions or best practices to make sure it doesn't interfere with anything)

**Comment by robbielyman** [comment]
hi! i'm not using neovim as my daily driver any more. i'd happily accept a PR for this, but it's not something i'm inclined to work on myself.
